package com.brainx.datasource.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.random.Random

actual class PlatformSecureValueCipher actual constructor() : SecureValueCipher {

    private val alias: String = "tickettribe.datastore.aesgcm"

    private fun getOrCreateSecretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEY_STORE).apply { load(null) }
        val existing = keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry
        if (existing != null) return existing.secretKey

        val keyGenerator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEY_STORE)
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(AES_KEY_SIZE_BITS)
            .setRandomizedEncryptionRequired(true)
            .build()
        keyGenerator.init(spec)
        return keyGenerator.generateKey()
    }

    @OptIn(ExperimentalEncodingApi::class)
    override fun encrypt(plainText: String): String {
        if (plainText.isEmpty()) return plainText

        val key = getOrCreateSecretKey()
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            // When using Android Keystore with AES/GCM and setRandomizedEncryptionRequired(true),
            // the IV must be generated by the Cipher, not supplied by the caller.
            init(Cipher.ENCRYPT_MODE, key)
        }

        val iv = cipher.iv

        val cipherBytes = cipher.doFinal(plainText.encodeToByteArray())
        val ivB64 = Base64.encode(iv)
        val ctB64 = Base64.encode(cipherBytes)

        return buildString {
            append(SecureValueCipherFormat.PREFIX)
            append(ivB64)
            append(SecureValueCipherFormat.SEPARATOR)
            append(ctB64)
        }
    }

    @OptIn(ExperimentalEncodingApi::class)
    override fun decrypt(cipherText: String): String {
        if (cipherText.isEmpty()) return cipherText
        if (!cipherText.startsWith(SecureValueCipherFormat.PREFIX)) return cipherText

        val payload = cipherText.removePrefix(SecureValueCipherFormat.PREFIX)
        val parts = payload.split(SecureValueCipherFormat.SEPARATOR)
        require(parts.size == 2) { "Invalid encrypted payload" }

        val iv = Base64.decode(parts[0])
        val ct = Base64.decode(parts[1])

        val key = getOrCreateSecretKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, javax.crypto.spec.GCMParameterSpec(GCM_TAG_SIZE_BITS, iv))

        val plainBytes = cipher.doFinal(ct)
        return plainBytes.decodeToString()
    }

    private companion object {
        private const val ANDROID_KEY_STORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"

        private const val AES_KEY_SIZE_BITS = 256

        private const val GCM_IV_SIZE_BYTES = 12
        private const val GCM_TAG_SIZE_BITS = 128
    }
}

